Get policy service principals
manelmontilla/altimeter pull request #3
Opened 2021-10-28 08:53 UTC by manelmontilla

This PR modifies the AssumeRolePolicyDocument of a role so it also takes into account the "Service" principals.

2021-11-03 11:07 UTC, jroimartin requested changes
Commits e9b8526, 6640b6c and 16c915c belong to #1 and 05ef73c belongs to #2 (although the commit id is actually different), but they have been included in this PR too. Probably you chose the wrong base when creating the PR.

2021-11-03 11:08 UTC, jroimartin requested changes
From my point of view, all the PRs should be independent and based on master, so it is easier for the Altimeter team to merge them.

2021-11-17 14:55 UTC, manelmontilla commented
> From my point of view, all the PRs should be independent and based on master, so it is easier for the Altimeter team to merge them.

Makes sense, done.

2021-11-18 09:22 UTC, jroimartin commented
👍

2021-11-24 10:34 UTC, closed without merging